language: julia
  - 1.5
  - nightly

matrix:
    - PYTHON=conda

matrix:
  allow_failures:
    - julia: nightly

before_install:
  - sudo apt-get install python3
  - which python
  - julia -e 'ENV["PYTHON"]="python"; using Pkg; Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("Conda"); using Conda; Conda.update(); Conda.add("numpy");'

script:
  - julia -e 'using Pkg; Pkg.instantiate(); Pkg.build(); Pkg.test(; coverage=true)';
  - make test_solutions

branches:
  only:
    - master

deploy:
  edge: true
  provider: pages:git
  deploy_key: github_deploy_key
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
