language: julia
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy

script:
  - make test_solutions

branches:
  only:
    - master

deploy:
  edge: true
  provider: pages:git
  deploy_key: github_deploy_key
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
