language: julia
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

# Install packages
install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy

script:
  - make test_solutions

branches:
  only:
    - master

deploy:
  edge: true
  provider: pages:git
  deploy_key: github_deploy_key
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
