language: julia
  - 1.5
  - nightly

env:
     global:
    - PYTHON=conda


before_install:
    #install mpmath to test functionallity
  - julia -e 'using Pkg; Pkg.add("Conda"); using Conda; Conda.add("numpy")';

matrix:
  allow_failures:
    - julia: nightly

script:
  - make test_solutions

branches:
  only:
    - master

deploy:
  edge: true
  provider: pages:git
  deploy_key: github_deploy_key
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
