language: julia
  - 1.5
  - nightly

matrix:
    - PYTHON=conda

matrix:
  allow_failures:
    - julia: nightly

script:
  - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.build("PyCall"); Pkg.test("PyCall"; coverage=true)';
  - make test_solutions

branches:
  only:
    - master

deploy:
  edge: true
  provider: pages:git
  deploy_key: github_deploy_key
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
