language: julia
  - 1.5
  - nightly

matrix:
  allow_failures:
    - julia: nightly

# Install packages
install:
  - (sudo apt-get -qq update && sudo apt-get install -y python python-pip && sudo pip install numpy)

script:
  - julia -e 'using Pkg; Pkg.instantiate()'
  - make test_solutions

branches:
  only:
    - master

deploy:
  edge: true
  provider: pages:git
  deploy_key: github_deploy_key
  skip_cleanup: true
  verbose: true
  local_dir: build
  on:
    branch: master
